#!/bin/sh
### BEGIN INIT INFO
# Provides:          mysqlxtra-server
# Required-Start:    $local_fs $network $named $time $syslog
# Required-Stop:     $local_fs $network $named $time $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Description:       mysqlxtra-server
### END INIT INFO

NAME='mysqlxtra-server'
MYSQL_XTRA_PORT={{ mysql_xtra_port }}
MYSQL_XTRA_ALLOW={{ mysql_xtra_allow }}
RUNAS=root

PIDFILE=/var/run/${NAME}.pid
LOGFILE=/var/log/${NAME}.log

start() {
  if [ -f ${PIDFILE} ] && kill -0 $(cat ${PIDFILE}); then
    echo 'Service already running' >&2
    return 1
  fi

  # check if log file exists
  if [ ! -e ${LOGFILE} ] ; then
    touch ${LOGFILE} && chown ${RUNAS}:${RUNAS} ${LOGFILE}
  fi

  echo 'Starting service...' >&2

  local CMD="/usr/bin/socat TCP4-LISTEN:${MYSQL_XTRA_PORT},fork,range=${MYSQL_XTRA_ALLOW} EXEC:/usr/sbin/${NAME} >> \"${LOGFILE}\" 2>&1 & echo \$!"
  su -c "${CMD}" ${RUNAS} > "${PIDFILE}"
  echo 'Service started' >&2
}

stop() {
  if [ ! -f "${PIDFILE}" ] || ! kill -0 $(cat "${PIDFILE}"); then
    echo 'Service not running' >&2
    return 1
  fi
  echo 'Stopping service...' >&2
  kill -15 $(cat "${PIDFILE}") && rm -f "${PIDFILE}"
  echo 'Service stopped' >&2
}

uninstall() {
  echo -n "Are you really sure you want to uninstall this service? That cannot be undone. [yes|No] "
  local SURE
  read SURE
  if [ "$SURE" = "yes" ]; then
    stop
    rm -f "${PIDFILE}"
    echo "Notice: log file is not be removed: '${LOGFILE}'" >&2
    update-rc.d -f ${NAME} remove
    rm -fv "$0"
  fi
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  uninstall)
    uninstall
    ;;
  restart)
    stop
    start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|uninstall}"
esac
